### ISSUE TITLE
Problem with laravel.cm

### ISSUE THREAD

**Issue by darwinnatha** [laravelcm/jobs-portail-issues#7]
I clone the project, install all the dependencies, i run the cmd `composer setup`. Like i use Laravel herd, i link it with `laravel.cm`, but when i open the site at `laravel.cm.test`
I can't access the website 
![image](https://github.com/user-attachments/assets/678af1e9-2bfe-4f49-9d92-eedd4f397509)
This is the error on all the url

**Comment by Stephen2304** [comment]
Can we see the result of the command line **composer setup** ?

**Comment by StevyMarlino** [comment]
Hello @darwinnatha, try to type `php artisan optimize:clear` after running your  `composer install`
hope that you have properly init the .env and also run the `npm install && npm run dev or npm run build`
best regard

**Comment by darwinnatha** [comment]
```.env
APP_NAME="Laravel Cameroun"
APP_ENV=local
APP_KEY=base64:Uule5OkLIN3xGtIQBRJGNpMw8w222V42b0vsYp7QSMU=
APP_DEBUG=true
APP_URL=http://laravel.cm.test
FILAMENT_PATH=cp

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravelcm
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=database
SESSION_DRIVER=database
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=no-reply@laravel.cm
MAIL_FROM_NAME="${APP_NAME}"

MAILGUN_DOMAIN=
MAILGUN_SECRET=

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GITHUB_REDIRECT=${APP_URL}/auth/github/callback

SLACK_WEBHOOK_URL=
SLACK_TEAM_NAME="Laravel Cameroun"
SLACK_API_TOKEN=
SLACK_TEAM_URL="https://laravelcm.slack.com"

MARKDOWNX_GIPHY_API_KEY=
TORCHLIGHT_TOKEN=
TORCHLIGHT_THEME=moonlight-ii
UNSPLASH_ACCESS_KEY=

TELEGRAM_BOT_TOKEN=
TELEGRAM_CHANNEL=

MEDIA_DISK=media
FILAMENT_FILESYSTEM_DISK=${MEDIA_DISK}

SENTRY_LARAVEL_DSN=
SENTRY_TRACES_SAMPLE_RATE=

NOTCHPAY_PUBLIC_KEY=
```

the `npm run build` doesn't work cause a large file when minifying so i use `npm run dev`
the `composer setup` migrate all the tables, seed the database and create the admin
  @StevyMarlino  I think you wanted to say `php artisan optimize:clear`

**Comment by darwinnatha** [comment]
And now i test the filament panel, it's work with no problem but it's too slow

**Comment by mckenziearts** [comment]
We build asset with yarn not npm. The projet need Torchlight API Key. And finally run vite to load the project.

**Comment by StevyMarlino** [comment]
You can close the issue if you have launch the project already. @darwinnatha

**Comment by darwinnatha** [comment]
@mckenziearts, @StevyMarlino  The problem persists.

**Comment by Stephen2304** [comment]
Try 
- **php artisan cache:clear**
- **php artisan view:clear**
- **php artisan config:cache**

**Comment by darwinnatha** [comment]
There's no change

**Comment by darwinnatha** [comment]
I delete the project, redo all the process from the start, but i got the same error page when loading

**Comment by StevyMarlino** [comment]
What's you environnement ?

**Comment by darwinnatha** [comment]
I'm on Windows 10,
