### ISSUE TITLE
Utilisation d'un cle speciale pour les articles, threads et forum 

### ISSUE THREAD

**Issue by darwinnatha** [laravelcm/jobs-portail-issues#8]
A la place du slug, il serait adoptable d'utiliser une cle speciale qui est immuable. Car si une personne partage un lien et qu'apres on modifie le titre d'un article. On se retrouvera avec un **404**. Je proposerais qu'il y'ait un systeme ( pas forcement UUID) pour rediriger le post avec le slug si possible.

Lien entre initialement `laravel.cm/redirect/{typo}/{cle-special}` et il se retrouve sur la  page du post ou thread...

**Comment by mckenziearts** [comment]
Dans la prochaine release qui sera effectué au plus tard semaine prochaine on ne pourra plus modifier l'article une fois qu'il sera créé, mais pour les discussions ou le forum on pourra les supprimer. Les liens de seo vont juste être régénérer après ça.

**Comment by darwinnatha** [comment]
Ok. Je crois que ce serait mieux de ne plus pouvoir modifier apres publication. Car apres creation on peut y voir un souci et on le refactor vite.
